
--EJERCICIO 5
UPDATE PROFESORADO SET fecha_nac='22/061974', antiguedad=4 WHERE nombre='ESTEFANIA';

--EJERCICO 6
UPDATE PROFESORADO SET antiguedad=antiguedad+1;

--EJERCICIO 8
DELETE FROM ALUMNADO WHERE cod_curso=3;

--EJERCICIO 9
ALTER TABLE ALUMNADO DROP CONSTRAINT Cod_alum_PK;
INSERT INTO ALUMNADO (Nombre, Apellidos, Sexo, Fecha_Nac) SELECT Nombre, Apellidos, Sexo, Fecha_Nac FROM ALUMNADO_NUEVO;

--EJERCICIO 10
UPDATE CURSOS SET max_alumn=(SELECT COUNT (*) FROM ALUMNADO WHERE cod_curso=2) WHERE codigo=2;

--EJERCICIO 11
DELETE FROM ALUMNADO WHERE cod_curso IN (SELECT Codigo FROM CURSOS WHERE cod_profe IN (SELECT Codigo FROM PROFESORADO WHERE Nombre='NURIA'));