CREATE OR REPLACE PROCEDURE MOVER_FAMILIA(NUM_IDENTIFICADOR_ORIGEN FAMILIAS.IDENTIFICADOR%TYPE, NUM_IDENTIFICADOR_DESTINO FAMILIAS.IDENTIFICADOR%TYPE)
AS
    V_VALIDO BOOLEAN;
BEGIN
    --COMPROBAMOS QUE EXISTEN DICHOS ID Y QUE NO SON PADRE E HIJA
    V_VALIDO := COMPROBAR_HIJA (NUM_IDENTIFICADOR_ORIGEN , NUM_IDENTIFICADOR_DESTINO);
    IF V_VALIDO = FALSE THEN
        UPDATE FAMILIAS SET FAMILIA=NUM_IDENTIFICADOR_DESTINO, OFICINA=NULL WHERE IDENTIFICADOR=NUM_IDENTIFICADOR_ORIGEN;
        DBMS_OUTPUT.PUT_LINE('SE HA MOVIDO LA FAMILIA DE ORIGEN A DESTINO');
        COMMIT;
    END IF;
    
END;
/
--CON ESTA FUNCIÓN COMPROBAMOS SI FAMILIA DESTINO ES HIJA DE ORIGEN Y A LA VEZ CONTROLAMOS QUE EXISTAN DICHAS FAMILIAS
create or replace FUNCTION COMPROBAR_HIJA(NUM_IDENTIFICADOR_ORIGEN FAMILIAS.IDENTIFICADOR%TYPE, NUM_IDENTIFICADOR_DESTINO FAMILIAS.IDENTIFICADOR%TYPE)
RETURN BOOLEAN
AS
    V_IDENTIFICADOR_ORIGEN FAMILIAS.IDENTIFICADOR%TYPE;
    CURSOR C_FAMILIA_DESTINO IS SELECT FAMILIA FROM FAMILIAS WHERE FAMILIA=NUM_IDENTIFICADOR_DESTINO;  
    V_VALIDO BOOLEAN;
BEGIN
    BEGIN
        SELECT IDENTIFICADOR INTO V_IDENTIFICADOR_ORIGEN FROM FAMILIAS WHERE IDENTIFICADOR=NUM_IDENTIFICADOR_ORIGEN;
        --RECORREMOS EL CURSOR Y COMPROBAMOS SI ID ORIGEN ES IGUAL A DESTINO, EN ESE CASO SON PADRE E HIJA
        FOR C IN C_FAMILIA_DESTINO LOOP
            IF C.FAMILIA=NUM_IDENTIFICADOR_ORIGEN THEN  
                DBMS_OUTPUT.PUT_LINE('LA FAMILIA DESTINO ES HIJA DE LA FAMILIA ORIGEN ');
                V_VALIDO := TRUE;
           ELSE                
                V_VALIDO := FALSE; 
           END IF;
        END LOOP;
        --CONTROLAMOS MEDIANTE EXCEPCIÓN QUE EXISTAN DATOS DE FAMILIA ORIGEN Y DESTINO
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('FAMILIA ORIGEN O DESTINO NO EXISTEN');
        WHEN OTHERS THEN
         DBMS_OUTPUT.PUT_LINE('NO EXISTE LA TABLA FAMILIA EN LA BASE DE DATOS');
    END;
   RETURN V_VALIDO; 
END;
/
--BLOQUE ANÓNIMO PRINCIPAL QUE SOLICITA ENTRADA DE IDS A USUARIO Y LO PASA COMO PARAMETROS AL PROCEDIMIENTO
DECLARE
    V_ID_OR FAMILIAS.IDENTIFICADOR%TYPE := &ORIGEN;
     V_ID_DES FAMILIAS.IDENTIFICADOR%TYPE := &DESTINO;
BEGIN
   MOVER_FAMILIA(V_ID_OR, V_ID_DES);
END;
/
